### ISSUE TITLE
munin vs. munin-node

### ISSUE THREAD

**Issue by tuxmea** [example42/puppet-tp#6]
The data structure for munin installs the node and configures the munin master.
data/munin/default.yaml
---
  munin::settings:
    package_name: 'munin-node'
    service_name: 'munin-node'

data/munin/osfamily/RedHat.yaml
---
  munin::settings:
    www_dir_path: '/var/www/html/munin'

I suggest to split this into munin (master) and munin-node.
(I wonder whether the minus sign is allowed in the name)

**Comment by alvagante** [comment]
This is a case where decisions have to be taken (and I still haven't decided...): how to manage applications which have different components such as munin, bacula, or other cases.
Probably is better to have different datasets in order to have complete freedom and avoid arbitrary choices. In this case they would be munin and munin-node (yes, minus is allowed). Would you send s PR with the fix?
